name: Build and test

# Run tests check on pull request or push to main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run jUnit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Create .env file
        run: touch .env

      - name: Build and run tests
        run: docker build -t build_image .

      - name: Copy code coverage report
        run: docker create --name build_container build_image && mkdir build && docker cp build_container:/src/homebrew-dash/build/reports/ ./build/reports/

      - name: Run code coverage
        uses: codecov/codecov-action@v3

        env:
          DEFAULT_BRANCH: main
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
